.TH MIPS-SIMULATOR 1
.SH NAME
mipc \- Assembles and interprets MIPS program
.SH SYNOPSIS
.B mipc
.IR file
.SH DESCRIPTION
.B MIPS Simulator
is a micro assembler and interpreter written for educational purpose by Bytes Club.
.SH CONFORMING TO
MIPS-IV
.SH EXIT CODES
.TP
.BR 0
 Program exited successfuly, no error encountered.
.TP
.BR 1
 Invalid file given, loading file content failed.
.TP
.BR 2
 Syntactical error, lexical analysis failed.
.TP
.BR 3
 Semantic error, parsing of tokens failed.
.TP
.BR 4
 Invalid operation encountered, execution failed.
.SH VERSION
.B 0.3.3
- For more details: https://yarnpkg.com/en/package/mips-simulator
.SH LICENSE
.B Copyright © 2017 Progyan Bhattacharya, Bytes Club
.PP
This program is free software\: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

