language: node_js
sudo: false
node_js:
  - "6"
  - "8"
os: linux
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  - yarn: true
  - eslint: true
  - node_modules
branches:
  only:
    - master
install:
  - npm install eslint
  - npm link
before_script:
  - npm run lint
script:
  - npm test
